language: node_js
node_js:
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  api_key:
    secure: n69Z3xHnuFMrt6KI3JCAaGrF89SkOmvTZbzTrfRoIHGgxG6e2KQvWOGEjoqrRKIL1nH4Lqt9m20cjEQ7VwZoLJTp48ycbJcrVY1bqcHSDTsMqkoR2catpMz/pPzUvPfpxZ29VoLnM5nYGl1FP6KlId5LVBZIceqnu7+PqlMc+VeoSlVpeRa6/yJJJWnovMmGG2FTiD0P+cG+Rx5HzHalsL2lDvCpUCoGk93qNUdrRmTptGLXxzIjjaSmU4iYA/HU/d2kaIoj4MRWMMr+t2JoHInoqoophD+YWR5oCeN96nLyPWfiG92Lg3OC/hJT6pdL8OzT+yt+yq6eUa3s208q8GOfyb97Xt7t5vF74xmvKaDjZwoWxoDwPDRFT4jukjq43649wqYlr1D9IQMHhADNir3HhVLq8WlMJs7350gNRQE/2ujXO5s6Ckth6V71Qr4pMgYRUgdt1fZobDD+FeYX8TbFOpvkzZ0TZ4iyZUnlloYNOxnamlkZJAU27bNWg/t6dcmbBi0mDLLaxKlU3hUobJv0qbnqAqcPedgjbD8w1ruMiKqIunY7mTKdiY2i+S/at9pQPnQnPhaJBAjg//h4EuCYoGmeMUHvRKnRgzmoVG7Rqo1pXYizMpwieLGWdSgyULsm9AEEZk3xfhGTD+o465Qk/tTMYeJOdTN9uBQpD+E=
